## 行列演算の基礎

- ベクトルの定義
- 行列の定義
- 転置の計算
- 逆行列
- 行列積

In [2]:
import numpy as np

In [3]:
## ベクトルの定義
x = np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [5]:
## 行列の定義
X = np.array([[1,2],[3,4]])　## このコードの[]書き方は、転置をした時の為に書いている。
print(X)

[[1 2]
 [3 4]]


In [8]:
## 転置
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [10]:
## 逆行列
# linear Algebra = 線形代数の事　linalg
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [12]:
## 行列積
XX_inv = np.dot(X, X_inv)
print(XX_inv)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


## Numpyでよく使う処理

In [24]:
X = np.array([
    [2,3,4],
    [5,6,7],
    [8,9,10],
    [11,12,13]
])

In [25]:
print(X)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [26]:
row, col = X.shape ##　行と列の番号が取れる

In [27]:
row

4

In [28]:
col

3

In [30]:
for x in X: ## for文で各行毎に出せる。
    print(x)
    print(' - - ')

[2 3 4]
 - - 
[5 6 7]
 - - 
[ 8  9 10]
 - - 
[11 12 13]
 - - 


## データの定義

In [3]:
X = np.array([
    [1,2,3],
    [1,2,5],
    [1,3,4],
    [1,5,9]
])

print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [4]:
## Yの定義

In [5]:
Y = np.array([
    [1],
    [5],
    [6],
    [8]
])

print(Y)

[[1]
 [5]
 [6]
 [8]]


In [6]:
# Step1

In [8]:
XtX = np.dot(X.T, X)
print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [12]:
# Step 2

In [11]:
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [13]:
# Step 3

In [15]:
XtY = np.dot(X.T, Y)
print(XtY)

[[ 20]
 [ 70]
 [124]]


In [16]:
# Step 4

In [18]:
W = np.dot(XtX_inv, XtY)
print(W)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]
