## Numpy 数値計算用ライブラリ

In [1]:
import numpy as np

In [2]:
##  ベクトルの定義
x = np.array([1,2,3])

In [3]:
x

array([1, 2, 3])

In [4]:
y = np.array([2,3.9,6.1])

In [5]:
y

array([2. , 3.9, 6.1])

## データの中心化

In [6]:
## 平均の算出
x.mean()

2.0

In [7]:
y.mean()

4.0

In [8]:
## 中心化
xc = x - x.mean()

In [9]:
xc

array([-1.,  0.,  1.])

In [10]:
yc = y - y.mean()

In [11]:
yc

array([-2. , -0.1,  2.1])

## パラメータaの計算

In [14]:
## 要素毎の掛け算（要素積）
xx = xc * xc

In [15]:
xx

array([1., 0., 1.])

In [19]:
xy = xc * yc

In [21]:
xy

array([ 2. , -0. ,  2.1])

In [22]:
xx.sum()

2.0

In [23]:
xy.sum()

4.1

In [24]:
a = xy.sum() / xx.sum()

In [25]:
a

2.05